image: golang:1.13-alpine

variables:
  REPO: gitlab.com
  GROUP: silenteer
  PROJECT: titan

  DOCKER_DRIVER: overlay2
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

stages:
  - test

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
  - go get -v -d ./...

test:
  image: golang:1.13-alpine
  stage: test
  before_script:
    - apk --no-cache add git make
  script:
#    - pwd
#    - ls -la
#    - go version
    - echo "Start NATS server"
    - wget "https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-amd64.zip"
    - unzip nats-server-v2.1.0-linux-amd64.zip
    - ./nats-server-v2.1.0-linux-amd64/nats-server &
    - make test
