image: golang:1.16.2-alpine3.13

variables:
  REPO: gitlab.com
  GROUP: silenteer
  PROJECT: titan

  DOCKER_DRIVER: overlay2
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

stages:
  - test

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
  - go get -v -d ./...

test:
  image: golang:1.16.2-alpine3.13
  stage: test
  before_script:
    - apk --no-cache add git make
  script:
    - echo "Start NATS server"
    - wget "https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-amd64.zip"
    - unzip nats-server-v2.1.0-linux-amd64.zip
    - ./nats-server-v2.1.0-linux-amd64/nats-server &

    - wget "https://releases.hashicorp.com/consul/1.9.4/consul_1.9.4_linux_amd64.zip"
    - unzip consul_1.9.4_linux_amd64.zip
    - ls -la
    - ./consul agent -dev &

    - go clean -testcache  && go test ./...  --count 1
