
image: golang:1.13-alpine

variables:
  REPO: gitlab.com
  GROUP: silenteer
  PROJECT: go-nats

  DOCKER_DRIVER: overlay2
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

stages:
  - test

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
  - go get -v -d ./...

unit_tests:
  image: golang:1.13-alpine
  stage: test
  before_script:
    - apk --no-cache add git make
  script:
    - pwd
    - ls -la
    - go version
    - go test -v ./... -coverprofile .testCoverage.txt

